[package]
name = "nekonomicon-core-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
thiserror = "1.0"                                   # Better error types
anyhow = "1.0"                                      # Error handling
serde = { version = "1.0", features = ["derive"] }  # If you need config files
colored = "2.0"                                     # For colored output
nekonomicon-core = { path = "../nekonomicon-core" }
