id = "nekonomicon"
name = "nekonomicon"
description = "Syntax highlighting and language support for nekonomicon (.purr) scripting language"
version = "0.0.1"
schema_version = 1
authors = ["VOID-DIV-0"]
repository = "https://github.com/VOID-DIV-0/nekonomicon-core"

[grammars.nekonomicon]
repository = "https://github.com/VOID-DIV-0/nekonomicon-core"
commit = "main"
path = "packages/nekonomicon-core-zed-extension/languages/nekonomicon"
